{"name": "test_login[data2]", "status": "passed", "attachments": [{"name": "log", "source": "8cb93b6f-e7d1-4c5e-855a-6c3b3031206c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'case_id': 'login_case_002', 'case_title': '用户输入正确的用户名、\\n错误的密码，点击登录', 'test_data': {'username': 'alive', 'password': 1234567}, 'exp': {'by': 'xpath', 'locater': \"//*[@id='common-prompt']/div/p\", 'exp_value': '密码错误'}}"}], "start": 1663419388088, "stop": 1663419394240, "uuid": "c5ed6420-f9f9-40b8-ac5a-8e39f30b2e28", "historyId": "178f5884c0b5708ea915e2eac7a5a413", "testCaseId": "c6db3f0583de5245fe1a62b1d735a86c", "fullName": "run.TestLogin#test_login", "labels": [{"name": "suite", "value": "run"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-5FKMFO0H"}, {"name": "thread", "value": "4888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "run"}]}