{"uuid": "cc1cc3f8-a5b6-4c91-817d-c180db068300", "children": ["18572e39-03e3-427c-8b46-060e2073bc87"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "broken", "statusDetails": {"message": "TypeError: Object of type module is not JSON serializable\n", "trace": "  File \"E:\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 893, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 778, in _call_with_optional_argument\n    func()\n  File \"E:\\Python_Learns\\WEB自动化测试框架\\test_case\\test_login.py\", line 23, in setup\n    self.main = Main()\n  File \"E:\\Python_Learns\\WEB自动化测试框架\\page\\basepage.py\", line 49, in __init__\n    self._driver.get(self.base_url)\n  File \"E:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"E:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"E:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 372, in execute\n    data = utils.dump_json(params)\n  File \"E:\\Python\\lib\\site-packages\\selenium\\webdriver\\remote\\utils.py\", line 33, in dump_json\n    return json.dumps(json_struct)\n  File \"E:\\Python\\lib\\json\\__init__.py\", line 231, in dumps\n    return _default_encoder.encode(obj)\n  File \"E:\\Python\\lib\\json\\encoder.py\", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"E:\\Python\\lib\\json\\encoder.py\", line 257, in iterencode\n    return _iterencode(o, 0)\n  File \"E:\\Python\\lib\\json\\encoder.py\", line 179, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\n"}, "start": 1663486256953, "stop": 1663486259172}], "start": 1663486256953, "stop": 1663486259340}